// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUm6EvHKbsFvrIZfkWoCPL0upY1NcEU_U',
    appId: '1:58217549704:web:3afa816df87beeb260743d',
    messagingSenderId: '58217549704',
    projectId: 'musicc-a3f7d',
    authDomain: 'musicc-a3f7d.firebaseapp.com',
    storageBucket: 'musicc-a3f7d.firebasestorage.app',
    measurementId: 'G-D4LN1EY867',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVXwDLGSGg0W2Na9H_hN4mc9iMA5MYCUc',
    appId: '1:58217549704:android:28360a8d5e5385e660743d',
    messagingSenderId: '58217549704',
    projectId: 'musicc-a3f7d',
    storageBucket: 'musicc-a3f7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXuuA45-uKPCbwxln9DaU1DlHXQ4KBZGU',
    appId: '1:58217549704:ios:10c2991f74704a3560743d',
    messagingSenderId: '58217549704',
    projectId: 'musicc-a3f7d',
    storageBucket: 'musicc-a3f7d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXuuA45-uKPCbwxln9DaU1DlHXQ4KBZGU',
    appId: '1:58217549704:ios:10c2991f74704a3560743d',
    messagingSenderId: '58217549704',
    projectId: 'musicc-a3f7d',
    storageBucket: 'musicc-a3f7d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUm6EvHKbsFvrIZfkWoCPL0upY1NcEU_U',
    appId: '1:58217549704:web:59b67942efb1c56860743d',
    messagingSenderId: '58217549704',
    projectId: 'musicc-a3f7d',
    authDomain: 'musicc-a3f7d.firebaseapp.com',
    storageBucket: 'musicc-a3f7d.firebasestorage.app',
    measurementId: 'G-CNY3QCFPTP',
  );
}
